# Generated by Django 3.1 on 2020-08-26 03:39

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(default='whatsapp link', max_length=700)),
                ('t_link', models.CharField(default='telegram link', max_length=700)),
                ('available', models.BooleanField()),
                ('description', models.TextField(default='Description')),
                ('pycoin_value', models.IntegerField()),
                ('image', models.TextField()),
                ('relate', models.CharField(default='ws/comp/self', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('mobile_no', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('fullname', models.CharField(default='Full name ', max_length=200)),
                ('pycoins', models.IntegerField(default=500)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Studymaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.TextField()),
                ('rating', models.CharField(max_length=5)),
                ('description', models.TextField(default='This will help you')),
                ('image', models.TextField()),
                ('relation', models.CharField(default='html+css/bootstrap/figma/git/sql/numpy', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('image', models.TextField()),
                ('description', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('level', models.CharField(default='beginner/Intermediate/Advance', max_length=100)),
                ('chapter', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('image', models.TextField(default='niranja preferably square image inte link ')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyweekapp.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Registeredevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyweekapp.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyweekapp.member')),
            ],
        ),
    ]
